name: Demo Workflow
on: workflow_dispatch

jobs: 
  print-demo:
    runs-on: ubuntu-latest
    steps: 
      - name: Print to console
        run: echo Hello from gitActions
      - name: Print a few lines
        run: |
          echo First line!
          echo Second line!
