name: Deploy React App
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cashe deps
        uses: actions/checkout@v3
          with:
            path: ~/.npm
            key: node-modules-${{ hashFile('**/package.json') }}    
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cashe deps
        uses: actions/checkout@v3
          with:
            path: ~/.npm
            key: node-modules-${{ hashFile('**/package.json') }}  
      - name: Install dependencies
        run: npm ci
      - name: Linter check
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cashe deps
        uses: actions/checkout@v3
          with:
            path: ~/.npm
            key: node-modules-${{ hashFile('**/package.json') }}          
      - name: Install dependencies
        run: npm ci
      - name: Build Runner
        run: npm run build
      - name: Deploy
        run: echo Success
      - name: navigate
        run: cd test
      - name: show file
        run: ls -la