name: Deploy React App
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Linter check
        run: npm run lint
      - name: Deploy
        run: echo Success
      - name: navigate
        run: cd test
      - name: show file
        run: ls -la


