name: Deploy React App
on: push

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
        node-version: [ 16.x, 18.x ]
        mongodb-version: [ '5.0', '6.0' ]
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
      - name: Linter check
        run: npm run lint
      - name: Deploy
        run: echo Success
      - name: install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
  mongo:
    needs: testing
    steps:
        - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: navigate
        run: |
          cd test
          echo files into test folder  
          ls
          python3 new.py
          python3 -m pytest -s -v


          
